name: Pull Request
on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run format
            - name: Test
              run: npm run test
            - name: Coverage
              uses: ziishaned/jest-reporter-action@v0.0.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-command: 'npm run test:ci'
            - name: Build
              run: npm run build
            - name: E2E
              uses: cypress-io/github-action@v1
              with:
                  start: npm run dev
                  wait-on: 'http://localhost:3000'
              env:
                  CI: true
    deploy:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v2
            - uses: amondnet/now-deployment@v2
              with:
                  zeit-token: ${{ secrets.NOW_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  zeit-team-id: team_wCLukMFMpi08J93bEKoK6iDX
                  now-args: ''
                  now-org-id: ${{ secrets.NOW_ORG_ID}}
                  now-project-id: ${{ secrets.NOW_PROJECT_ID}}
