name: Pull Request
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

steps:
- uses: actions/checkout@v2
- name: Use Node.js
  uses: actions/setup-node@v1
  with:
    node-version: '12.x'
  - name: Install dependencies
    run: npm ci
  - name: Lint
    run: npm run format
  - name: Build
    run: npm run build
